version: '3.3'
services:
  rethink:
    image: rethinkdb
    #container_name: postgis_floti
    ports:
      - "28015:28015"
    #environment:
    #  - POSTGRES_USER=logi
  starlight:
    build: ./api